// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_QhuFjklwOo5HDB0oolO1Zjy6pf6OlSA',
    appId: '1:660294089940:web:093cc80b9479d473100f41',
    messagingSenderId: '660294089940',
    projectId: 'flutter-firebase-c0711',
    authDomain: 'flutter-firebase-c0711.firebaseapp.com',
    storageBucket: 'flutter-firebase-c0711.appspot.com',
    measurementId: 'G-4WMLXSCCPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWfOO5HkYnBaH_egEVojtsz-Jku9naInI',
    appId: '1:660294089940:android:5ab4cef202e7bd2c100f41',
    messagingSenderId: '660294089940',
    projectId: 'flutter-firebase-c0711',
    storageBucket: 'flutter-firebase-c0711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgllALk3nGAr37m9H01ZKzNYn1FgLySWk',
    appId: '1:660294089940:ios:e4cd607473a859cb100f41',
    messagingSenderId: '660294089940',
    projectId: 'flutter-firebase-c0711',
    storageBucket: 'flutter-firebase-c0711.appspot.com',
    androidClientId: '660294089940-eaavsau5h3j8pr8c29p7pm771t7fs98u.apps.googleusercontent.com',
    iosClientId: '660294089940-nlii3pp9m03if8k4jemqjd43dn6j45ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartparkingAdminWebPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgllALk3nGAr37m9H01ZKzNYn1FgLySWk',
    appId: '1:660294089940:ios:e4cd607473a859cb100f41',
    messagingSenderId: '660294089940',
    projectId: 'flutter-firebase-c0711',
    storageBucket: 'flutter-firebase-c0711.appspot.com',
    androidClientId: '660294089940-eaavsau5h3j8pr8c29p7pm771t7fs98u.apps.googleusercontent.com',
    iosClientId: '660294089940-nlii3pp9m03if8k4jemqjd43dn6j45ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartparkingAdminWebPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_QhuFjklwOo5HDB0oolO1Zjy6pf6OlSA',
    appId: '1:660294089940:web:047c73423cf47665100f41',
    messagingSenderId: '660294089940',
    projectId: 'flutter-firebase-c0711',
    authDomain: 'flutter-firebase-c0711.firebaseapp.com',
    storageBucket: 'flutter-firebase-c0711.appspot.com',
    measurementId: 'G-MPNPNG2ZQF',
  );
}
